name: Python application test with Github Actions

on:
  push:

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9.18
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest and flake8
        run: |
          pip install pytest flake8

      - name: Run tests
        run: |
          pytest
            - name: Test with pytest
              run: |
                flake8